language: ruby
before_install:
  - "gem install rjack-tarpit -v=2.1.2"
  - "gem install bundler -v=1.17.3"
install: "bundle _1.17.3_ install --jobs=3 --retry=3"
sudo: false
dist: trusty
rvm:
  - 2.3.8
  - 2.5.3
  - ruby-head
  - jruby-9.1.17.0
  - jruby-9.2.5.0
script: "bundle exec rake test"
matrix:
  allow_failures:
    - rvm: ruby-head
