language: ruby
before_install: "gem install rjack-tarpit -v=2.1.2"
install: "bundle install --jobs=3 --retry=3"
sudo: false
dist: trusty
rvm:
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - ruby-head
  - rbx
  - jruby-9.1.15.0
  - jruby-head
script: "bundle exec rake test"
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx
    - rvm: jruby-head
