language: ruby
before_install:
  - "gem install rjack-tarpit -v'~>2.1' || \
      ( sleep 1; gem install rjack-tarpit -v'~>2.1' ) || \
      ( sleep 5; gem install rjack-tarpit -v'~>2.1' )"
  - "gem install bundler --version 1.13.7"
install: "bundle _1.13.7_ install --retry=3"
sudo: false
rvm:
  - 2.1.9
  - 2.2.6
  - 2.3.3
  - ruby-head
  - rbx
  - jruby-1.7.26
  - jruby-9.1.6.0
  - jruby-head
script: "bundle exec rake test"
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx
    - rvm: jruby-head
