language: ruby
before_install: "gem install rjack-tarpit -v'~>2.1' || \
      ( sleep 1; gem install rjack-tarpit -v'~>2.1' ) || \
      ( sleep 5; gem install rjack-tarpit -v'~>2.1' )"
bundler_args: ""
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - rbx
  - jruby
  - jruby-head
script: "bundle exec rake test"
matrix:
  allow_failures:
    - rvm: rbx
    - rvm: jruby-head
