language: ruby
before_install: "gem install rjack-tarpit -v=2.1.1"
install: "bundle install --jobs=3 --retry=3"
sudo: false
rvm:
  - 2.2.6
  - 2.3.3
  - ruby-head
  - rbx
  - jruby-1.7.26
  - jruby-9.1.8.0
  - jruby-head
script: "bundle exec rake test"
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx
    - rvm: jruby-head
