#!/bin/sh

### BEGIN INIT INFO
# Provides:          iyyov
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Should-Start:      $named
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Iyyov jruby monitor
# Description:       Iyyov jruby monitoring and job control daemon
### END INIT INFO

set -e

. /lib/lsb/init-functions

# Gem home directory
# Set to match system "jgem environment path"
gem_home="/usr/local/lib/jruby/gems"

# (Exact) Gem version of iyyov to run
version="1.1.3"

# User to run the daemon as (should own rundir)
user="runr"

# Running directory (for jobs.rb config, log, and pid file)
rundir="/var/local/runr/iyyov"

prog="iyyov"
daemon="${gem_home}/gems/iyyov-${version}-java/init/${prog}"
config="${rundir}/jobs.rb"
pidfile="${rundir}/${prog}.pid"

RETVAL=0

start() {
    [ -x "$daemon" ] || exit 5
    [ -f "$config" ] || exit 6
    [ -d "$rundir" ] || exit 7

    log_daemon_msg "Starting rsync daemon" "rsync"
    start-stop-daemon --start -d $rundir -c $user --exec $daemon -- $config
    RETVAL=$?
    log_end_msg $RETVAL
}

status() {
    if [ -f "$pidfile" ]; then
        pid=`cat $pidfile`
        echo "Status $prog: running pid $pid"
    else
        echo "Status $prog: not running"
    fi
}

reload() {
    if [ -e "$pidfile" ]; then
        touch $config
    fi
}

stop() {
    log_daemon_msg "Stopping iyyov daemon" "iyyov"
    start-stop-daemon --stop --quiet --oknodo --pidfile $pidfile
    RETVAL=$?
    log_end_msg $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status
        ;;
    reload)
        reload
        ;;
    restart)
        stop
        start
        RETVAL=$?
        ;;
    condrestart)
        [ -e $pidfile ] && restart
        RETVAL=$?
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|reload|restart|condrestart}"
        RETVAL=1
esac

exit $RETVAL
